### ISSUE TITLE
ZeroScope XL errors

### ISSUE THREAD

**Issue by Ainaemaet** [tin2tin/Generative_AI#28]
Hello, 

I am receiving the following error when trying to generate using the ZeroscopeXL model (all other models work fine except the polyware-ai ones which seem to have been removed from huggingspace). 

`Q:\Users\username\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py:1369: FutureWarning: You are trying to load the model files of the `variant=fp16`, but no such modeling files are available.The default model files: {'vae/diffusion_pytorch_model.bin', 'text_encoder/pytorch_model.bin', 'unet/diffusion_pytorch_model.bin'} will be loaded instead. Make sure to not load from `variant=fp16`if such variant modeling files are not available. Doing so will lead to an error in v0.22.0 as defaulting to non-variantmodeling files is deprecated.
  deprecate("no variant default", "0.22.0", deprecation_message, standard_warn=False)
unet\diffusion_pytorch_model.safetensors not found
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:08<00:00,  1.61s/it]
Traceback (most recent call last):
  File "Q:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Generative_AI-main\__init__.py", line 826, in execute
    video_frames = pipe(
  File "Q:\Users\username\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: VideoToVideoSDPipeline.__call__() got an unexpected keyword argument 'height'
Error: Python: Traceback (most recent call last):
  File "Q:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Generative_AI-main\__init__.py", line 826, in execute
    video_frames = pipe(
  File "Q:\Users\username\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: VideoToVideoSDPipeline.__call__() got an unexpected keyword argument 'height'`

I'm sorry I have no idea how to fix it.

**Comment by tin2tin** [comment]
Ref: https://github.com/huggingface/diffusers/issues/3937

**Comment by tin2tin** [comment]
Thanks for testing. This should be fixed now.
