### ISSUE TITLE
AnimateDiff errors

### ISSUE THREAD

**Issue by Ainaemaet** [tin2tin/Generative_AI#29]
Hello again, 

Didn't realize AnimateDiff was in the model list now so gave it a try and getting more errors: 

`Warning: 1 x Draw window and swap: 115.6337 ms, average: 115.63369998 ms
Traceback (most recent call last):
  File "Q:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Generative_AI-main\__init__.py", line 763, in execute
    pipe = DiffusionPipeline.from_pretrained(
  File "Q:\Users\username\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 908, in from_pretrained
    cached_folder = cls.download(
  File "Q:\Users\username\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1330, in download
    info = model_info(
  File "Q:\Users\username\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "Q:\Users\username\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'camenduru/AnimateDiff/'. Use `repo_type` argument if needed.
Error: Python: Traceback (most recent call last):
  File "Q:\Users\username\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Generative_AI-main\__init__.py", line 763, in execute
    pipe = DiffusionPipeline.from_pretrained(
  File "Q:\Users\username\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 908, in from_pretrained
    cached_folder = cls.download(
  File "Q:\Users\username\AppData\Roaming\Python\Python310\site-packages\diffusers\pipelines\pipeline_utils.py", line 1330, in download
    info = model_info(
  File "Q:\Users\username\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "Q:\Users\username\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'camenduru/AnimateDiff/'. Use `repo_type` argument if needed.`

My python knowledge is limited but it's a good learning experience, so I will try to figure them out myself in the meantime as I wait for a response; just wanted to bring them to your attention so you can see what issues might crop up for users!

**Comment by tin2tin** [comment]
That should not be exposed. Sorry. Removed now.
