### ISSUE TITLE
macOS install dependency error

### ISSUE THREAD

**Issue by enzyme69** [tin2tin/Generative_AI#3]
running Blender on macOS, while running "install dependency" it gives me error:

```
Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.5/scripts/addons/text_to_video-main/__init__.py", line 133, in install_modules
    exec("import torch")
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.5/scripts/addons/text_to_video-main/__init__.py", line 243, in execute
    install_modules(self)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.5/scripts/addons/text_to_video-main/__init__.py", line 141, in install_modules
    subprocess.check_call(
  File "/Applications/Blender.app/Contents/Resources/3.5/python/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Applications/Blender.app/Contents/Resources/3.5/python/bin/python3.10', '-m', 'pip', 'install', 'torch', '--index-url', 'https://download.pytorch.org/whl/cu118', '--no-warn-script-location', '--user']' returned non-zero exit status 1.



```

**Comment by tin2tin** [comment]
Thanks for trying this add-on out. I'm not on Mac, so I can't test it myself, but apparently fails the installation of the torch module on Mac. So, I'll need your help, to try to install pytorch on your computer, and if you find a way, and you document you steps, I can implement that, so others can benefit from your findings.

Question is what version of pytorch will work. There is a Blender add-on to install modules. Get this: https://github.com/amb/blender_pip In this add-on, you can install and remove pyton modules. A life saver.

There is a tutorial here, maybe you can find a newer one, but if possible stick to pip(which is what the above mentioned add-on and my add-on uses).

Hopefully, it's a smooth walk for you. Good luck.

**Comment by tin2tin** [comment]
the tutorial: https://sebastianraschka.com/blog/2022/pytorch-m1-gpu.html

**Comment by enzyme69** [comment]
I installed the blender_pip addon, and then pip install the torch and torchvision module.

Then I got new error:
```
Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.5/scripts/addons/text_to_video-main/__init__.py", line 243, in execute
    install_modules(self)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.5/scripts/addons/text_to_video-main/__init__.py", line 180, in install_modules
    import_module(self, "soundfile", "PySoundFile")  # Sox for Linux pip install sox
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.5/scripts/addons/text_to_video-main/__init__.py", line 89, in import_module
    show_system_console(True)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.5/scripts/addons/text_to_video-main/__init__.py", line 29, in show_system_console
    ctypes.windll.user32.ShowWindow(
AttributeError: module 'ctypes' has no attribute 'windll'
```

**Comment by tin2tin** [comment]
Ah, yes, I'm using some windows specific functions to show the system console when things are being rendered/downloaded/installed. I need to disable that for mac/linux, I guess.

Can you check if PySoundFile works on Mac?

Can you give me the pip commands you used for install torch and torchvision on a mac?

**Comment by tin2tin** [comment]
I change the installation of torch to the default on mac and linux. I hope cuda is included and working for you if you went with the default version too?

I hope there shouldn't be any windows speciffic code anymore. Let me know how it goes.

**Comment by tin2tin** [comment]
Did you have any time to delve deeper?

**Comment by tin2tin** [comment]
I'm closing this for now. Reopen it, if it still doesn't work.

**Comment by enzyme69** [comment]
I downloaded the latest version and now getting new error:

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.5/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.5/scripts/addons/Generative_AI-main/__init__.py", line 988, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "GeneratorAddonPreferences" registration error: 'audio_model_card' EnumProperty could not register (see previous error)

```

**Comment by tin2tin** [comment]
My bad. Try re-downloading it now.

**Comment by tin2tin** [comment]
If there is something not covered in the Win install instruction for MacOS, then let me know, so I can add it.
