### ISSUE TITLE
error when installing dependencies

### ISSUE THREAD

**Issue by vuaieo** [tin2tin/Generative_AI#32]
1. hi i installed git but not sure what you mean with PATH, rthen i started blender as administrator and clicked on install dependecys and this error came:

Traceback (most recent call last):
  File "C:\Users\vuaieo\AppData\Roaming\UPBGE\Blender\3.6\scripts\addons\Generative_AI-main\__init__.py", line 516, in execute
    install_modules(self)
  File "C:\Users\vuaieo\AppData\Roaming\UPBGE\Blender\3.6\scripts\addons\Generative_AI-main\__init__.py", line 330, in install_modules
    subprocess.check_call([pybin,"-m","pip","install","numpy","--upgrade"])
  File "C:\Users\vuaieo\Desktop\upbge-0.36-windows-x86_64\3.6\python\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\vuaieo\\Desktop\\upbge-0.36-windows-x86_64\\3.6\\python\\bin\\python.exe', '-m', 'pip', 'install', 'numpy', '--upgrade']' returned non-zero exit status 1.
Info: Installing: bark module.
Info: Installing: xformers module.
Info: Installing: imageio module.
Info: Installing: imwatermark module.
Error: Python: Traceback (most recent call last):
  File "C:\Users\vuaieo\AppData\Roaming\UPBGE\Blender\3.6\scripts\addons\Generative_AI-main\__init__.py", line 516, in execute
    install_modules(self)
  File "C:\Users\vuaieo\AppData\Roaming\UPBGE\Blender\3.6\scripts\addons\Generative_AI-main\__init__.py", line 330, in install_modules
    subprocess.check_call([pybin,"-m","pip","install","numpy","--upgrade"])
  File "C:\Users\vuaieo\Desktop\upbge-0.36-windows-x86_64\3.6\python\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\vuaieo\\Desktop\\upbge-0.36-windows-x86_64\\3.6\\python\\bin\\python.exe', '-m', 'pip', 'install', 'numpy', '--upgrade']' returned non-zero exit status 1.

2. there was some conflict with the deepbump addon so i removed it and then i was able start install dependencies

3.  well but looks like i was able finaly to generate sound with bark : )

**Comment by Ainaemaet** [comment]
Not sure if it might help but I had some similar dependency errors the first time I tried installing, and re-running the 'install dependencies' seemed to clear them up. 

Shout out to @tin2tin for keeping at this project. I'm absolutely flummoxed this isn't being used everywhere atm, it makes things so much easier to create something cohesive!!
