### ISSUE TITLE
macOS non cuda non transformer

### ISSUE THREAD

**Issue by enzyme69** [tin2tin/Generative_AI#35]
Unfortunately not working without CUDA isn't ... is there anyway to run this without CUDA NVidia? Maybe will try in the future.

```
Blender PIP user site: /Users/jimmygunawan/.local/lib/python3.10/site-packages
user_site_packages /Users/jimmygunawan/.local/lib/python3.10/site-packages
user_site_packages /Users/jimmygunawan/.local/lib/python3.10/site-packages
register_class(...):
Warning: 'gpencil.camera_controls_pie' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'gpencil.snc_tools' does not contain '_MT_' with prefix and suffix
init
init
2023-08-08 15:00:49.185 Blender[28835:821251] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
init
Read blend: "/Users/jimmygunawan/Desktop/genAI_test_001.blend"
init
Downloading (…)ain/model_index.json: 100%|█████| 384/384 [00:00<00:00, 2.38MB/s]
vae/diffusion_pytorch_model.safetensors not found
Downloading (…)cial_tokens_map.json: 100%|██████| 460/460 [00:00<00:00, 498kB/s]
Downloading (…)cheduler_config.json: 100%|█████| 465/465 [00:00<00:00, 1.50MB/s]
Downloading (…)_encoder/config.json: 100%|█████| 609/609 [00:00<00:00, 3.71MB/s]
Downloading (…)fad/unet/config.json: 100%|█████| 727/727 [00:00<00:00, 5.97MB/s]
Downloading (…)okenizer_config.json: 100%|█████| 737/737 [00:00<00:00, 8.47MB/s]
Downloading (…)tokenizer/merges.txt: 100%|███| 525k/525k [00:00<00:00, 9.49MB/s]
Downloading (…)8fad/vae/config.json: 100%|█████| 636/636 [00:00<00:00, 8.95MB/s]
Downloading (…)tokenizer/vocab.json: 100%|█| 1.06M/1.06M [00:00<00:00, 2.71MB/s]
Downloading (…)on_pytorch_model.bin: 100%|███| 167M/167M [00:42<00:00, 3.96MB/s]
Downloading pytorch_model.bin: 100%|█████████| 681M/681M [01:53<00:00, 5.97MB/s]
Downloading (…)on_pytorch_model.bin: 100%|█| 2.82G/2.82G [07:01<00:00, 6.70MB/s]
Fetching 12 files: 100%|████████████████████████| 12/12 [07:04<00:00, 35.35s/it]
Loading pipeline components...: 100%|█████████████████████████| 5/5 [00:01<00:00,  3.72it/s]
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Generative_AI-main/__init__.py", line 2969, in execute
    pipe.enable_xformers_memory_efficient_attention()
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1641, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1667, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1657, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 193, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers
Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Generative_AI-main/__init__.py", line 2969, in execute
    pipe.enable_xformers_memory_efficient_attention()
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1641, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1667, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1657, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 227, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 223, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 220, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/Users/jimmygunawan/.local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 193, in set_use_memory_efficient_attention_xformers
    raise ModuleNotFoundError(
ModuleNotFoundError: Refer to https://github.com/facebookresearch/xformers for more information on how to install xformers

```

**Comment by tin2tin** [comment]
I don't have a Mac, so I can't test it. Try to comment out those line giving you an error, and see how far you'll be able to go.

**Comment by tin2tin** [comment]
I've added to the readme that MacOS is unsupported(for the reason mentioned above), so I'll close this now.
